// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import NestedFormController from "./nested_form_controller"
import Autofocus from "./autofocus_controller"
import Autosearch from "./autosearch_controller"
import debounced from 'debounced' 

debounced.initialize()

application.register("hello", HelloController)
application.register("nested-form", NestedFormController)
application.register("autofocus", Autofocus)
application.register("autosearch", Autosearch)

import { Dropdown, Modal, Tabs, Popover, Toggle, Slideover } from "tailwindcss-stimulus-components"
application.register('dropdown', Dropdown)
application.register('modal', Modal)
application.register('tabs', Tabs)
application.register('popover', Popover)
application.register('toggle', Toggle)
application.register('slideover', Slideover)